mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('secondapp/', include('secondapp.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
]

pages/urls.py
# pages/urls.py
from django.urls import path
from . import views
app_name = "pages"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('hello/', views.hello, name="hello"),
    path('name/', views.name, name="name"),
    path('introduce/', views.introduce, name="introduce"),
    path('classRandomChoice/', views.classRandomChoice, name="classRandomChoice"),
    path('yourname/<str:name>/', views.yourname, name="yourname"),
    path('urlcopy/<str:name>/<int:age>', views.urlcopy, name="urlcopy"),
    path('multiply/<int:num1>/<int:num2>', views.multiply, name="multiply"),
    path('multipletable/<int:big>/<int:small>', views.multipletable, name="multipletable"),
    path('dtl/', views.dtl, name="dtl"),
    path('forif/', views.forif, name="forif"),
    path('loop/', views.loop, name="loop"),
    path('throw/', views.throw, name="throw"),
    path('catch/', views.catch, name="catch"),
    path('lottoT/', views.lottoT, name="lottoT"),
    path('lottoC/', views.lottoC, name="lottoC"),
    path('artii/', views.artii, name="artii"),
    path('result/', views.result, name="result"),
]

secondapp/urls.py
# secondapp/urls.py
from django.urls import path
from . import views
app_name = "secondapp"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('static_example/', views.static_example, name="static_example"),
]

secondapp/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render
import random
from datetime import datetime
import requests
# Create your views here.

def index(request):
    return render(request, 'pages/index.html')

def hello(request):
    menu = ['닭갈비', '탕수육', '초밥', '스파게티돈가스']
    pick = random.choice(menu)
    return render(request, 'pages/hello.html', {'pick':pick})

def name(request):
    my_name = '김성현'
    return render(request, 'pages/name.html', {'my_name':my_name})

def introduce(request):
    my_info = ['김성현', '28', '서울 관악구', 'https://github.com/kim-svadoz']
    name = my_info[0]
    age = my_info[1]
    home = my_info[2]
    git = my_info[3]
    context = {
        'name' : name,
        'age' : age,
        'home' : home,
        'git' : git
    }
    return render(request, 'pages/introduce.html', context)

def classRandomChoice(request):
    arr = ['백승재', '심재민', '유환우', '강인선', '신승환']
    pick = random.choice(arr)
    context = {
        'pick' : pick
    }
    return render(request, 'pages/classRandomChoice.html', context)

def yourname(request, name):
    name = name
    context={
        'name' : name
    }
    return render(request, 'pages/yourname.html', context)

def urlcopy(request, name, age):
    name = name
    age = age
    context={
        'name' : name,
        'age' : age
    }
    return render(request, 'pages/urlcopy.html', context)

def multiply(request, num1, num2):
    num1 = num1
    num2 = num2
    result = num1 * num2
    context = {
        'num1' : num1,
        'num2' : num2,
        'result' : result
    }
    return render(request, 'pages/multiply.html', context)

def multipletable(request, big, small):
    result = []
    if(big < small):
        big, small = small, big
    for num in range(1, small+1):
        result.append(big*num)
    context={
        'result' : result
    }
    return render(request, 'pages/multipletable.html', context)

def dtl(request):
    mList = ['짜장면', '차돌짬뽕', '탕수육', '콩국수']
    empty_list = []
    mString = "Life is short, You need Python"
    today = datetime.now()
    context = {
        'mList' : mList,
        'empty_list' : empty_list,
        'mString' : mString,
        'today' : today
    }
    return render(request, 'pages/dtl.html', context)

# 1. 간단한 반복문으로 리스트 각 요소를 출력
# 2. if, else 활용해서 문자열 비교
# 2-1. 내가 넘긴 문자열과 특정한 문자열 비교
# 3. if, elif, else 사용해보기
# 3-1. 문자열의 길이가 5 이하이면 short
# 3-2. 문자열의 길이가 10 이상이면 long
# 3-3. 모두 아니면 적당 출력

# 모두 작성했다면,
## 1) 반복문으로 리스트 각 요소를 출력해서
## 2) 해당 요소가 90 이상이면 A
## 3) 해당 요소가 70 이상이면 B
## 4) 그 외엔 C 출력
def forif(request):
    mList = [100, 50, 80, 71, 10]
    mString = '간단한 문자열zzzzzzzzzzzz'
    mInput = input("문자열을 입력하세요: ")
    data_a = '첫번째 데이터'
    data_b = '두번째 데이터'
    data_a, data_b = data_b, data_a
    context = {
        'mList' : mList,
        'mString' : mInput,
        'data_a' : data_a,
        'data_b' : data_b
    }
    return render(request, 'pages/forif.html', context)

def loop(request):
    nums = []
    for data in range(10):
        nums.append(data)
    context = {
        'nums': nums
    }
    return render(request, 'pages/loop.html', context)

def throw(request):
    return render(request, 'pages/throw.html')

def catch(request):
    # request parameter는 요청 정보가 담겨있다.
    # request.GET == 딕셔너리와 유사하다.
    # request.GET != dict()
    # data = request.GET['message']
    name = request.GET.get('name')
    age = request.GET.get('age')
    context ={ 
        'name' : name,
        'age' : age
    }
    return render(request, 'pages/catch.html', context)

# 1. 사용자가 숫자 입력
# 2. 입력 받은 횟수 만큼 반복해서
# 3. 리스트에 로또 번호 담는다.
# 3-1. random.sample(range(1, 46), 6)
# 4. 사용자가 입력한 숫자와 로또번호가 담긴 리스트를 출력
# 5. ul태그를 사용하여 각 번호들을 한줄 씩 출력
def lottoT(request):
    return render(request, 'pages/lottoT.html')

def lottoC(request):
    num = int(request.GET.get('num'))
    lottos = []
    for data in range(num):
        lottos.append(random.sample(range(1, 46), 6))
    context={
        'num' : num,
        'lottos' : lottos,
    }

    return render(request, 'pages/lottoC.html', context)

def artii(request):
    return render(request, 'pages/artii.html')

def result(request):
    msg = request.GET.get('msg')
    result = requests.get(f'http://artii.herokuapp.com/make?text={msg}').text
    context = {
        'result' : result
    }
    return render(request, 'pages/result.html', context)

secondapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'secondapp/index.html')

def static_example(request):
    return render(request, 'secondapp/static_example.html')

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>
    {% block title %}
      Document
    {% endblock %}
  </title>
</head>
<body>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
</body>
</html>

pages/templates/pages/artii.html
<h1> 아스키 아트 </h1>
<form action="{% url 'result' %}">
  영어만 입력해 주세요. : <input type="text" name="msg">
  <input type="submit" value="제출">
</form>

pages/templates/pages/catch.html
{% extends 'base.html' %}
{% block title %}
데이터 받았다.
{% endblock %}

{% block body %}
<p>{{ name }}, {{ age }}</p>
{% endblock %}

pages/templates/pages/dtl.html
<h1>1. for문</h1>
{% for food in mList %}
  <p> {{ forloop.counter }}.{{ food }} </p>
{% endfor %}

{% for data in empty_list %}
  <p>data</p>
{% empty %}
  <p>비어있습니다.</p>
{% endfor %}
<hr>

<h1>2. 조건문</h1>
{% for food in mList %}
  {% if food == '짜장면' %}
    <p>짜장면엔 고춧가루지 아암 이게맞지</p>
  {% else %}
    <p>뭔 소리야 {{ food }}을 먹어줘야지</p>
  {% endif %}
{% endfor %}
<hr>

{% for food in mList %}
  {% if forloop.first %}
    <p> {{forloop.first}} </p>
    <p> {{forloop.last}} </p>
    <p>짜장면엔 고춧가루지 아암 이게맞지</p>
  {% else %}
    <p>뭔 소리야 {{ food }}을 먹어줘야지</p>
  {% endif %}
{% endfor %}
<hr>

<h1>3. filter 활용</h1>
  <p>{{ mString|lower }}</p>
  <p>{{ mString|upper }}</p>
  <p>{{ mString|title }}</p>
  <p>{{ mString|length }}</p>
  <p>{{ mString|truncatewords:3 }}</p>
  <p>{{ mString|truncatechars:10 }}</p>
<hr>

<h1>4. lorem ipsum</h1>
<p>{% lorem %}</p>
<p>{% lorem 3 w %}</p>
<p>{% lorem 3 p %}</p>

pages/templates/pages/forif.html
<h1>간단한 반복문으로 리스트 출력</h1>
{% for data in mList %}
  {% if data >= 90 %}
  <P>{{ data }} : A</P>
  {% elif data >= 70%}
  <P>{{ data }} : B</P>
  {% else %}
  <p>{{ data }} : C</p>
  {% endif %}
{% endfor %}
<hr>

<h1>문자열의 길이</h1>
{% if mString|length <= 5 %}
  <p>{{ mString|title }} : short</p>
{% elif mString|length >= 10 %}
  <p>{{ mString|title }} : long</p>
{% else %}
  <p>{{ mString|title }} : 적당</p>
{% endif %}

pages/templates/pages/hello.html
<h1>오늘 점심 메뉴는 {{pick}}</h1>

pages/templates/pages/index.html
{% extends 'base.html' %}
{% block title %}
  pagesIndex
{% endblock %}

{% block body %}
  <h1>Hello World 1</h1>
  <a href="{% url 'secondapp:index' %}">secondapp 인덱스</a>
{% endblock %}

pages/templates/pages/introduce.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Infomation</title>
  <style>
    .git{
      position: fixed;
      margin: auto;
      font-size: medium;
      right: 100px;
      bottom: 100px;
    }
  </style>
</head>
<body>
  <h1>나의 이름은 {{name}}이고, 나이는 {{age}}이며 {{home}}에 거주하고 있습니다.<h1>
  </br>

  <div class="git">
    {{git}}
  </div>
</body>
</html>

pages/templates/pages/loop.html
<h1>페이지 만들기 복습</h1>
<ol>
  {% for num in nums %}
  <li>{{ num }}</li>
  {% endfor %}

</ol>

pages/templates/pages/lottoT.html
<h1> 로또 번호를 입력해주세용~ </h1>
<form action="{% url 'lottoC' %}">
  <label for="buy"> 구매 하고자 하는 갯수 : </label>
  <input type="number" name="num" id="buy">
  <input type="submit" value="제출" >
</form>

pages/templates/pages/multipletable.html
<p>{{result}}</p>
<h1>Django Temlplate Lagnuage ( DTL )</h1>

<!--  -->
{# 이게 DTL의 주석 #}
{% comment %}
DTL의 주석은 개발자모드(F12) 에서도 보이지 않는다!
여기는 전부
출력이 안됨... 주석임!
되도록이면 template에서는 주석사용 XX
{% endcomment %}

{% for num in result %}
  <p>{{num}}</p>
{% endfor %}

pages/templates/pages/multiply.html
URL로 받은 숫자1 : {{num1}} , 숫자2 : {{num2}}

곱한 값 => {{result}}

pages/templates/pages/name.html
<h1>나의 이름은 {{ my_name }}</h1>

pages/templates/pages/throw.html
{% extends 'base.html' %}
{% block title %}
던진다.
{% endblock %}

{% block body %}
<form action="{% url 'catch' %}" method="GET">
  이름 : <input type="text" name="name">
  나이 : <input type="number" name="age">
  <input type="submit" value="제출">
</form>
{% endblock %}

pages/templates/pages/urlcopy.html
<h2>URL로 입력받은 이름 : {{name}}, 나이 : {{age}}</h2>

secondapp/templates/secondapp/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}
    <title>Second App !</title>
  {% endblock %}
</head>
<body>
  {% block body %}
    <h1>Hello World 2</h1>
    <a href="{% url 'pages:index' %}">firstapp index</a>
  {% endblock %}
</body>
</html>

secondapp/templates/secondapp/static_example.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <img src="{% static 'secondapp/images/arin.jpg' %}" alt="">
{% endblock %}